version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 59695:5432
    environment:
      POSTGRES_USER: postgres_challenge
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nestjs_challenge
    networks:
      - challenge
    
  test-db:
    image: postgres:13
    ports:
      - 5051:5000
    environment:
      POSTGRES_USER: postgres_challenge
      POSTGRES_PASSWORD: 123123456789
      POSTGRES_DB: nestjs_challenge
    networks:
      - challenge
networks:
  challenge: